### ISSUE TITLE
Loginpage

### ISSUE THREAD

**Issue by chris-yooo** [chris-yooo/capstone-chrat-reloaded#10]
## Complexity

Large

## Tasks

- [ ] Create branch
- [ ] security changes in BE
- [ ] add loginpage in FE
- [ ] test edgecases within FE
- [ ] valid input in BE
- [ ] add tests in BE
