### ISSUE TITLE
GET EP with authtoken for WS

### ISSUE THREAD

**Issue by chris-yooo** [chris-yooo/capstone-chrat-reloaded#11]
## Complexity

Large

## Tasks

- [ ] Create branch
- [ ] create GET endpoint or use Loginpage EP
- [ ] generate token
- [ ] add token assign to WS session
- [ ] add method that send token to backend to auth the WS session
