### ISSUE TITLE
add pic upload

### ISSUE THREAD

**Issue by chris-yooo** [chris-yooo/capstone-chrat-reloaded#13]
## Complexity

Medium | Large

## Tasks

- [ ] Create branch
- [ ] frontend abbility to laod picture into chat
- [ ] saved them in a covered folder
- [ ] backend string with position and name from it
