### ISSUE TITLE
Profile Pictures in ChatMessages

### ISSUE THREAD

**Issue by chris-yooo** [chris-yooo/capstone-chrat-reloaded#25]
## Complexity

Medium

## Tasks

- [ ] Create branch
- [ ] BE changes
- [ ] record
- [ ] message json body
- [ ] tests
- [ ] FE change
- [ ] message json body
- [ ] styling from messages more visible
