### ISSUE TITLE
Change message body

### ISSUE THREAD

**Issue by chris-yooo** [chris-yooo/capstone-chrat-reloaded#26]
## Complexity

Medium

## Tasks

- [ ] Create branch
- [ ] change the appearance of the message body so that with 4 messages from one person only 1 datetime and username are there
- [ ] FE changes for that
- [ ] maybe BE changes ..
