### ISSUE TITLE
websocket & MongoDB

### ISSUE THREAD

**Issue by chris-yooo** [chris-yooo/capstone-chrat-reloaded#4]
## Tasks

- [ ] Create branch
- [ ] add dep for websockets
- [ ] add chatservice
- [ ] add websocket configuration
- [ ] add service for save to mongo db
- [ ] add interface for mongo
- [ ] add tests
