### ISSUE TITLE
Change Message to JSON obj

### ISSUE THREAD

**Issue by chris-yooo** [chris-yooo/capstone-chrat-reloaded#9]
## Complexity

Large

## Tasks

- [ ] Create branch
- [ ] add author to message json
- [ ] add message content to message json
- [ ] add datetime to message json
- [ ] add or reconfigure test
